modify electrolysis to a multi link
doneachh/pypsa-earth pull request #8
Opened 2024-12-03 15:35 UTC by doneachh

# Closes # (if applicable).

## Changes proposed in this Pull Request
added config flags, colors and technology
changed electrolysis to multilink

## Checklist

- [ ] I consent to the release of this PR's code under the AGPLv3 license and non-code contributions under CC0-1.0 and CC-BY-4.0.
- [ ] I tested my contribution locally and it seems to work fine.
- [ ] Code and workflow changes are sufficiently documented.
- [ ] Newly introduced dependencies are added to `envs/environment.yaml` and `doc/requirements.txt`.
- [ ] Changes in configuration options are added in all of `config.default.yaml` and `config.tutorial.yaml`.
- [ ] Add a test config or line additions to `test/` (note tests are changing the config.tutorial.yaml)
- [ ] Changes in configuration options are also documented in `doc/configtables/*.csv` and line references are adjusted in `doc/configuration.rst` and `doc/tutorial.rst`.
- [ ] A note for the release notes `doc/release_notes.rst` is amended in the format of previous release notes, including reference to the requested PR.

2025-01-08 13:16 UTC, energyLS requested changes
@doneachh the review is complete. Great start with this project, please consider my two remarks. Thank you!

2025-01-08 13:16 UTC, energyLS commented on scripts/prepare_sector_network.py
> +                efficiency2=costs.at["desalination", "efficiency"],
Please use an efficiency describing the ratio of water to hydrogen. If you have it, remember to also consider the efficiency of hydrogen to electricity, so in the end you get the efficiency of water to electricity as the field `efficiency2` intends to incorporate :)

For now, you can fetch the water-hydrogen-efficiency from the config. In the long term, it should/could be from technology-data.

2025-01-08 13:16 UTC, energyLS commented on scripts/prepare_sector_network.py
>          )
Please also add H2O buses. This could be done very similar to: https://github.com/pypsa-meets-earth/pypsa-earth/blob/main/scripts/prepare_sector_network.py#L196

2025-01-14 08:09 UTC, doneachh commented
@energyLS commited your proposed changes - I'm not hundert percent sure about the water buses as water isn't fitting to any of the pypsa components.

2025-01-14 13:36 UTC, energyLS requested changes
Two minor comments remaining

2025-01-14 13:36 UTC, energyLS commented on scripts/prepare_sector_network.py
> +            efficiency2=snakemake.config["sector"]["hydrogen"]["ratio_water_hydrogen"]
Please add the electricity to hydrogen efficiency in the calculation of `efficiency2`. If I see this correctly, you are using the efficiency from water to hydrogen, but you need water to electricity (since this is bus2 to bus1).

2025-01-14 13:36 UTC, energyLS commented on scripts/prepare_sector_network.py
> +def add_with_water_network(n, costs):
Why "with" water network? How about
```suggestion
def add_water_network(n, costs):

```

2025-01-14 15:24 UTC, doneachh commented on scripts/prepare_sector_network.py
> +            efficiency2=snakemake.config["sector"]["hydrogen"]["ratio_water_hydrogen"]
@energyLS Dont we have water to electricity through the / 33 as we calculate from kg H2 to kWh H2 or do you think, we also need to consider the costs.at["electrolysis", "efficiency"] in efficiency2? I left it out as I thought we would then calculate it two times (one time in the electrolysis and one time in the desalination)

2025-01-14 15:24 UTC, doneachh commented on scripts/prepare_sector_network.py
> +def add_with_water_network(n, costs):
agree!

2025-01-15 09:32 UTC, energyLS commented on scripts/prepare_sector_network.py
> +            efficiency2=snakemake.config["sector"]["hydrogen"]["ratio_water_hydrogen"]
@doneachh it has to be included, since `efficiency2` refers to the electricity. In the desalination part we account for the electricity required for desalination, in my point of view those are seperate parts :)

2025-01-15 12:21 UTC, doneachh commented on scripts/prepare_sector_network.py
> +            efficiency2=snakemake.config["sector"]["hydrogen"]["ratio_water_hydrogen"]
alright - i have added it! :)

2025-01-15 12:56 UTC, energyLS approved these changes
@doneachh thank you, approved. When testing, we should pay special focus on wether those efficiencies and how we applied them are correct.

2025-01-16 14:10 UTC, merged